This is phase 1 

In [1]:
import numpy as np


In [2]:
arr_1d=np.array([1,2,3,4,5,]) # one parameter required  
print(arr_1d)

[1 2 3 4 5]


In [5]:
arr_2d=np.array([[1,2,3],[4,5,6]]) # there must be equalence bw row and cols 
print(arr_2d)


[[1 2 3]
 [4 5 6]]


numpy arr vs list

In [9]:
py_list=[1,2,3]
print("This is multiplication of list :" ,py_list*2)

py_np_arr=np.array(([1,2,3]))
print("This is multiplication of np arr :" ,py_np_arr*2)

This is multiplication of list : [1, 2, 3, 1, 2, 3]
This is multiplication of np arr : [2 4 6]


In [13]:
arng = np.arange(0,10,2)
print(arng)

arng = np.arange(10000)
print(arng)

[0 2 4 6 8]
[   0    1    2 ... 9997 9998 9999]


In [14]:
zero= np.zeros((3,4))
print(zero)

[[0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]]


In [15]:
ones = np.ones((3,3))
print(ones)

[[1. 1. 1.]
 [1. 1. 1.]
 [1. 1. 1.]]


In [ ]:
random = np.random.random((1,5))
print(random)


[[0.87441383 0.26107573 0.35707166 0.90569449 0.4903708 ]]


In [ ]:
full = np.full((1,5),7) # start stop step
print(full)

[[7 7 7 7 7]]


In [ ]:
# vector , matics, tensor
vector = np.array([1,3,4,5])
matric = np.array([[1,3],[4,5]])
tensor = np.array([[1,3],[4,5] ,[1,2]]) # r,c equal
print(vector)
print(matric)
print(tensor)

[1 3 4 5]
[[1 3]
 [4 5]]
[[1 3]
 [4 5]
 [1 2]]
