### numpy operation


In [ ]:
import pandas as pd
import numpy as np
# work on indexing 
arr=np.array([10,9,8,7,6,5,4,3,2,1])
print(arr[2:7]) # first wala lia 
print(arr[2:8:2]) # last wala nhi liya 
print(arr[-3]) # last se 3rd (without 0)


[8 7 6 5 4]
[8 6 4]
3


In [ ]:
arr_2d=np.array([[1,2,3],
                 [4,5,6],
                 [9,8,7]])

print("specific element :",arr_2d[1,2])
print("Entire row :", arr_2d[2])
print("Entire column :", arr_2d[:,2]) # :, for all row


Entire row : [9 8 7]
Entire column : [3 6 7]


### Sorting


In [37]:
unsorted=np.array([[5,2,3],
                  [6,4,3],
                  [2,8,6]])
print(np.sort(unsorted, axis=1
))


[[2 3 5]
 [3 4 6]
 [2 6 8]]


### Filtering 


In [38]:
number= np.array([1,2,3,4,5,6,7,8])
even_num=number[number%2==0]
print(even_num)

[2 4 6 8]


### where


In [41]:
where_res=np.where(number>5)
print(where_res) #where_res=np.where(number>5)
print(number[where_res]) #[6 7 8]]

(array([5, 6, 7]),)
[6 7 8]


In [42]:
where_res=np.where(number>5, number*2,number)
# where_res=np.where(number>5, number*2,number)
#                    condition,true , false (like turnery)

print(where_res)

[ 1  2  3  4  5 12 14 16]


### array remove and add


In [47]:
# concatinate 
arr1=np.arange(10)
arr2=np.arange(5)
print(np.concatenate((arr1,arr2)))


[0 1 2 3 4 5 6 7 8 9 0 1 2 3 4]


In [48]:
# compability
print(arr1.shape==arr2.shape)

False


In [56]:
# add new cols and row 
orignal=np.array([[1,2],[3,4]])
new_row=np.array([[1,2]])
new_cols=np.array([[4],[6]])
print(np.vstack([orignal,new_row]))
print(np.hstack([orignal,new_cols]))



[[1 2]
 [3 4]
 [1 2]]
[[1 2 4]
 [3 4 6]]


In [58]:
# dletion
arr=np.arange(10)
remove=np.delete(arr,3)
print(remove)

[0 1 2 4 5 6 7 8 9]
